name: build

on: [push, workflow_dispatch]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      # create directory structure for container control directory
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          repository: Adanelia/krita-docker-env
          ref: build
      - name: Prepare env
        run: |
          mv krita-docker-env krita-auto-1
          cd krita-auto-1
          mkdir persistent
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          path: krita-auto-1/persistent
      - name: Build the docker image and run the container
        run: |
          cd krita-auto-1
          # download the deps archive
          ./bin/bootstrap-deps.sh
          # build docker img
          ./bin/build_image
          ./bin/run_container
          # clean
          rm -rf ./persistent/deps/_install
          # enter the docker container and build
          ./bin/enter_and_build
      - name: List dir
        run: ls -lh krita-auto-1/persistent
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.5.0
        with:
          name: linux
          path: krita-auto-1/persistent/*.AppImage
          retention-days: 1
